const http=require('http');
const {URL}=require('url');
const PORT=process.env.PORT||10000;
const ASHNA='https://api.ashna.ai/v1/api';

const html=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#0b1020"><title>Ashna AI Developer v3</title><style>
*{box-sizing:border-box}body{margin:0;background:#0b1020;color:#eef3ff;font:14px system-ui}.app{max-width:760px;margin:auto;padding:14px 14px 90px}.head{display:flex;gap:10px;align-items:center;margin:6px 0 14px}.logo{width:42px;height:42px;border-radius:13px;background:linear-gradient(135deg,#7c3aed,#2563eb);display:grid;place-items:center;font-weight:900}.head h1{margin:0;font-size:18px}.muted{color:#95a3ba}.card{background:#121a2a;border:1px solid #26344c;border-radius:16px;padding:14px;margin:10px 0}.card h2{font-size:13px;margin:0 0 10px}.row{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.grow{flex:1;min-width:0}.input,.txt{width:100%;background:#09101c;color:#fff;border:1px solid #2d3c56;border-radius:11px;padding:11px}.txt{min-height:110px;resize:vertical}.btn{border:1px solid #34435e;background:#1a263a;color:#fff;border-radius:11px;padding:10px 12px;font-weight:700}.primary{background:linear-gradient(135deg,#7c3aed,#4f46e5);border-color:#7c3aed}.btn:disabled{opacity:.45}.drop{border:1px dashed #435271;border-radius:12px;padding:18px;text-align:center;background:#0b1422}.notice{padding:9px;border:1px solid #2a3a54;border-radius:10px;background:#101827;white-space:pre-wrap}.hidden{display:none!important}.preview{height:420px;border:1px solid #26344c;border-radius:12px;overflow:hidden;background:white}.preview iframe{width:100%;height:100%;border:0}.status{position:fixed;left:0;right:0;bottom:0;background:#0a101cee;border-top:1px solid #26344c;padding:10px 14px}.status>div{max-width:760px;margin:auto;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ok{border-color:#14532d}.bad{border-color:#7f1d1d}</style></head><body>
<div class="app"><div class="head"><div class="logo">A</div><div><h1>Ashna AI Developer v3</h1><div class="muted">No save step • key used directly</div></div></div>
<section class="card"><h2>1 · ASHNA KEY</h2><input id="key" type="password" class="input" placeholder="Paste Ashna API key"><div class="row" style="margin-top:8px"><button type="button" class="btn primary" onclick="testKey(this)">Test Connection</button><button type="button" class="btn" onclick="loadModels()">Load Models</button></div><div id="conn" class="notice" style="margin-top:8px">Paste key. It is stored only in this browser if Remember is on.</div><label class="muted" style="display:block;margin-top:8px"><input id="remember" type="checkbox" checked> Remember on this device</label><label class="muted" style="display:block;margin-top:10px">Model</label><input id="model" list="models" class="input" value="ashna-x1"><datalist id="models"></datalist></section>
<section class="card"><h2>2 · PROJECT</h2><label class="drop" style="display:block;cursor:pointer"><b>Tap to choose HTML/code file</b><div class="muted">TTUM .html चुन सकते हो</div><input id="file" type="file" accept=".html,.htm,.js,.css,.txt,.json" hidden onchange="pickFile(this)"></label><div id="meta" class="notice hidden" style="margin-top:8px"></div><div class="row" style="margin-top:8px"><button type="button" class="btn grow" onclick="blankApp()">＋ New Blank App</button><button type="button" id="undo" class="btn" onclick="undoLast()" disabled>Undo</button></div></section>
<section class="card"><h2>3 · TELL AI</h2><textarea id="task" class="txt" placeholder="क्या बनाना/बदलना है लिखो"></textarea><div class="row" style="margin-top:8px"><button type="button" class="btn" onclick="voice()">🎤</button><button type="button" id="build" class="btn primary grow" onclick="buildApp()" disabled>▶ BUILD / MODIFY</button></div></section>
<section class="card"><h2>4 · RESULT</h2><div id="out" class="notice">Ready.</div><div class="row" style="margin-top:8px"><button type="button" class="btn" onclick="preview()">↻ Preview</button><button type="button" id="download" class="btn primary grow" onclick="downloadFile()" disabled>Download Updated File</button></div><div class="preview" style="margin-top:8px"><iframe id="frame"></iframe></div></section></div>
<div class="status"><div id="status">V3 ready</div></div>
<script>
var S={name:'',current:'',before:''};
function g(id){return document.getElementById(id)}
function keyNow(){return g('key').value.trim()}
function st(t){g('status').textContent=t}
function updateUI(){var k=keyNow();g('build').disabled=!(k&&S.current&&g('model').value.trim());g('undo').disabled=!S.before;g('download').disabled=!S.current;g('meta').classList.toggle('hidden',!S.current);if(S.current)g('meta').textContent=S.name+' · '+(new Blob([S.current]).size/1024).toFixed(1)+' KB'}
function persistKey(){var k=keyNow();if(g('remember').checked&&k)localStorage.setItem('ashna_v3_key',k);else localStorage.removeItem('ashna_v3_key');updateUI()}
g('key').addEventListener('input',persistKey);g('remember').addEventListener('change',persistKey);g('model').addEventListener('input',updateUI);
async function api(path,opt,timeoutMs){opt=opt||{};timeoutMs=timeoutMs||15000;var k=keyNow();if(!k)throw new Error('API key missing');var c=new AbortController();var timer=setTimeout(function(){c.abort()},timeoutMs);try{opt.signal=c.signal;opt.headers=Object.assign({},opt.headers||{},{Authorization:'Bearer '+k});var r=await fetch(path,opt);var tx=await r.text();var j;try{j=JSON.parse(tx)}catch(e){j={raw:tx}}if(!r.ok)throw new Error((j.error&&j.error.message)||j.message||('HTTP '+r.status));return j}catch(e){if(e.name==='AbortError')throw new Error('Timed out');throw e}finally{clearTimeout(timer)}}
window.testKey=async function(btn){persistKey();var b=btn||null;if(b)b.disabled=true;g('conn').className='notice';g('conn').textContent='Testing…';st('Testing Ashna connection…');try{var j=await api('/api/models',{},15000);var a=((j&&j.data)||j.models||[]);g('conn').className='notice ok';g('conn').textContent='✓ Connection works. '+a.length+' models returned.';st('Connection OK');fillModels(a)}catch(e){g('conn').className='notice bad';g('conn').textContent='Connection failed: '+e.message;st('Connection failed')}finally{if(b)b.disabled=false;updateUI()}}
function fillModels(arr){var a=(arr||[]).map(function(x){return typeof x==='string'?x:(x.id||x.name)}).filter(Boolean);g('models').innerHTML='';a.forEach(function(x){var o=document.createElement('option');o.value=x;g('models').appendChild(o)});if(a.length&&a.indexOf(g('model').value)<0)g('model').value=a[0];updateUI()}
window.loadModels=async function(){persistKey();g('conn').textContent='Loading models…';st('Loading models…');try{var j=await api('/api/models',{},15000);var a=((j&&j.data)||j.models||[]);fillModels(a);g('conn').className='notice ok';g('conn').textContent='✓ '+a.length+' models loaded.';st('Models loaded')}catch(e){g('conn').className='notice bad';g('conn').textContent='Could not load models: '+e.message;st('Model load failed')}}
window.pickFile=async function(inp){var f=inp.files&&inp.files[0];if(!f)return;S.name=f.name;S.current=await f.text();S.before='';preview();updateUI();g('out').textContent='File loaded. अब task लिखो.';st('Project loaded')}
window.blankApp=function(){S.name='new_app.html';S.current='<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>New App</title></head><body><h1>New App</h1></body></html>';S.before='';preview();updateUI();g('out').textContent='Blank app ready.';st('Blank app ready')}
function extract(s){var fence=String.fromCharCode(96).repeat(3),i=s.indexOf(fence);if(i<0)return s.trim();var nl=s.indexOf('\n',i+3),start=nl>=0?nl+1:i+3,end=s.indexOf(fence,start);return (end>=0?s.slice(start,end):s.slice(start)).trim()}
window.buildApp=async function(){persistKey();var task=g('task').value.trim(),m=g('model').value.trim();if(!task){alert('Task लिखो');return}if(!m){alert('Model ID डालो');return}if(!S.current){alert('Project file चुनो');return}S.before=S.current;updateUI();g('build').disabled=true;g('out').textContent='AI working…';st('AI working…');var sys='You are a senior coding engineer. Preserve unrelated working behavior, IDs, handlers, UI and data logic. Make only the requested change. Return ONLY the COMPLETE updated file contents in one code fence. Do not omit sections or use placeholders.';var prompt='TASK:\n'+task+'\n\nFILENAME: '+S.name+'\n\nCURRENT COMPLETE FILE:\n'+S.current;try{var j=await api('/api/chat/completions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:m,messages:[{role:'system',content:sys},{role:'user',content:prompt}],temperature:0.1})},120000);var msg=j&&j.choices&&j.choices[0]&&j.choices[0].message&&j.choices[0].message.content;if(!msg)throw new Error('Empty model response');var code=extract(typeof msg==='string'?msg:JSON.stringify(msg));if(code.length<Math.min(500,S.current.length*.2))throw new Error('Incomplete file returned; original kept.');S.current=code;preview();updateUI();g('out').textContent='✓ Updated file ready.';st('Done')}catch(e){S.current=S.before;S.before='';updateUI();g('out').textContent='Error: '+e.message+'\nOriginal kept.';st('Error: '+e.message)}}
window.undoLast=function(){if(!S.before)return;S.current=S.before;S.before='';preview();updateUI();g('out').textContent='Last AI change undone.';st('Undo complete')}
window.preview=function(){if(!S.current)return;g('frame').srcdoc=/\.html?$/i.test(S.name)?S.current:'<pre style="white-space:pre-wrap;padding:16px">'+S.current.replace(/[&<>]/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;'}[m]})+'</pre>'}
window.downloadFile=function(){if(!S.current)return;var a=document.createElement('a');a.href=URL.createObjectURL(new Blob([S.current],{type:'text/plain;charset=utf-8'}));a.download=S.name.replace(/(\.[^.]+)$/,'_AI$1');a.click();setTimeout(function(){URL.revokeObjectURL(a.href)},1000)}
window.voice=function(){var R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){alert('Voice typing Chrome में available नहीं है');return}var r=new R();r.lang='hi-IN';r.interimResults=true;var base=g('task').value.trim();r.onstart=function(){st('Listening…')};r.onresult=function(e){var t='';for(var i=e.resultIndex;i<e.results.length;i++)t+=e.results[i][0].transcript;g('task').value=(base?base+' ':'')+t};r.onend=function(){st('Voice captured')};r.start()}
(function(){var k=localStorage.getItem('ashna_v3_key')||'';if(k)g('key').value=k;updateUI()})();
</script></body></html>`;

function send(res,s,b,t='text/plain; charset=utf-8'){res.writeHead(s,{'Content-Type':t,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer'});res.end(b)}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');console.log(req.method,u.pathname);if(u.pathname==='/'||u.pathname==='/index.html')return send(res,200,html,'text/html; charset=utf-8');if(u.pathname==='/health')return send(res,200,'ok');if(!u.pathname.startsWith('/api/'))return send(res,404,'Not found');const auth=req.headers.authorization;if(!auth||!auth.startsWith('Bearer '))return send(res,401,JSON.stringify({error:{message:'Missing API key'}}),'application/json');const chunks=[];let size=0;for await(const c of req){size+=c.length;if(size>30*1024*1024)return send(res,413,JSON.stringify({error:{message:'Request too large'}}),'application/json');chunks.push(c)}const body=chunks.length?Buffer.concat(chunks):undefined;const target=ASHNA+u.pathname.slice(4)+u.search;const headers={Authorization:auth,Accept:'application/json'};if(req.headers['content-type'])headers['Content-Type']=req.headers['content-type'];const timeout=u.pathname.includes('chat/completions')?120000:15000;const ctrl=new AbortController();const timer=setTimeout(()=>ctrl.abort(),timeout);let r;try{r=await fetch(target,{method:req.method,headers,body:(req.method==='GET'||req.method==='HEAD')?undefined:body,redirect:'follow',signal:ctrl.signal})}catch(e){if(e.name==='AbortError')return send(res,504,JSON.stringify({error:{message:'Ashna upstream timeout'}}),'application/json');throw e}finally{clearTimeout(timer)}const buf=Buffer.from(await r.arrayBuffer());res.writeHead(r.status,{'Content-Type':r.headers.get('content-type')||'application/json','Cache-Control':'no-store'});res.end(buf)}catch(e){send(res,500,JSON.stringify({error:{message:e.message||'Proxy error'}}),'application/json')}});
server.listen(PORT,()=>console.log('Ashna mobile v3 listening on '+PORT));